---
layout: reference
section: learn
title: FromException
permalink: /learn/ref/Microsoft.Coyote.Threading.Tasks/ControlledTask/FromException
---
# ControlledTask.FromException method (1 of 2)

Creates a [`ControlledTask`](../ControlledTaskType) that is completed with a specified exception.

```csharp
public static ControlledTask FromException(Exception exception)
```

| parameter | description |
| --- | --- |
| exception | The exception with which to complete the task. |

## Return Value

The faulted task.

## See Also

* class [ControlledTask](../ControlledTaskType)
* namespace [Microsoft.Coyote.Threading.Tasks](../ControlledTaskType)
* assembly [Microsoft.Coyote](../../MicrosoftCoyoteAssembly.md)

---

# ControlledTask.FromException&lt;TResult&gt; method (2 of 2)

Creates a [`ControlledTask`](../ControlledTask-1Type) that is completed with a specified exception.

```csharp
public static ControlledTask<TResult> FromException<TResult>(Exception exception)
```

| parameter | description |
| --- | --- |
| TResult | The type of the result returned by the task. |
| exception | The exception with which to complete the task. |

## Return Value

The faulted task.

## See Also

* class [ControlledTask&lt;TResult&gt;](../ControlledTask-1Type)
* class [ControlledTask](../ControlledTaskType)
* namespace [Microsoft.Coyote.Threading.Tasks](../ControlledTaskType)
* assembly [Microsoft.Coyote](../../MicrosoftCoyoteAssembly.md)

<!-- DO NOT EDIT: generated by xmldocmd for Microsoft.Coyote.dll -->
